[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  # set these values in Netlify UI or replace with secrets
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""
  SUPABASE_SERVICE_ROLE_KEY = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
